### PR TITLE
Adding more metascraper packages and upgrading micro

### PR DESCRIPTION
**Pull request by oyeanuj**
Hey @mxstbr, I made some updates and upgrades to metascraper on my own fork and was wondering if it is something that you want in the base fork as well? 

If yes, here is a PR all set :)

The main changes -
1. Add more community rules than just the default.
2. Upgrade dependencies including that of metascraper
3. Upgrading to micro v9.

### CODE REVIEW

**Review by mxstbr — COMMENTED** [review]
This looks great, thanks so much! Will this have the same resulting JSON structure as before?

**Comment by oyeanuj** [comment]
I think so? Here is what it looks like
> https://micro-open-graph-kbkxlohlro.now.sh/?url=http://spectrum.chat

```json
// 20180708153309
// https://micro-open-graph-kbkxlohlro.now.sh/?url=http://spectrum.chat

{
  "author": null,
  "date": null,
  "description": "The community platform for the future.",
  "image": "https://spectrum.chat/img/apple-icon-144x144-precomposed.png",
  "logo": "http://spectrum.chat/img/apple-icon-144x144-precomposed.png",
  "publisher": "LogologoLogoLogo",
  "title": "Spectrum",
  "url": "http://spectrum.chat",
  "lang": null,
  "video": null
}
```

**Comment by mxstbr** [comment]
> ```
>   "publisher": "LogologoLogoLogo",
> ```

😆

**Review by mxstbr — APPROVED** [review]
Thanks so much! :pray:

**Pull request merged**
